/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booksuppliersapp;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author KHA
 */
public class BookSuppliers extends javax.swing.JFrame {

    /**
     * Creates new form BookSuppliers
     */
    static final String url= "jdbc:sqlserver://localhost:1433;databaseName=dbBookSuppliers";
    static final String user = "sa";
    static final String pass = "123"; 
    public BookSuppliers() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnfirst = new javax.swing.JPanel();
        lbtitle = new javax.swing.JLabel();
        pnCenter1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        chebBooks = new javax.swing.JCheckBox();
        chebNewpapers = new javax.swing.JCheckBox();
        chebJournalsandMagazines = new javax.swing.JCheckBox();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblRemarks = new javax.swing.JLabel();
        jsrpRemarks = new javax.swing.JScrollPane();
        jTxtaRemarks = new javax.swing.JTextArea();
        pnCentre2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        pnLast = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnfirst.setBackground(new java.awt.Color(0, 102, 51));
        pnfirst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbtitle.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbtitle.setForeground(new java.awt.Color(255, 255, 255));
        lbtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitle.setText("Books Suppliers");

        javax.swing.GroupLayout pnfirstLayout = new javax.swing.GroupLayout(pnfirst);
        pnfirst.setLayout(pnfirstLayout);
        pnfirstLayout.setHorizontalGroup(
            pnfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnfirstLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtitle)
                .addGap(247, 247, 247))
        );
        pnfirstLayout.setVerticalGroup(
            pnfirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnfirstLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtitle)
                .addContainerGap())
        );

        pnCenter1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblID.setText("Suppliers ID:");

        txtID.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        txtName.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblName.setText("Suppliers Name:");

        lblType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblType.setText("Suppliers Type:");

        chebBooks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chebBooks.setText("Books");

        chebNewpapers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chebNewpapers.setText("News Papers");

        chebJournalsandMagazines.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chebJournalsandMagazines.setText("Journals and Magazines");

        lblAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAddress.setText("Address :");

        txtAddress.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        txtContactNo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        lblContactNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblContactNo.setText("Contact No :");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmail.setText("Email :");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        lblRemarks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRemarks.setText("Remarks:");

        jTxtaRemarks.setColumns(20);
        jTxtaRemarks.setRows(5);
        jsrpRemarks.setViewportView(jTxtaRemarks);

        javax.swing.GroupLayout pnCenter1Layout = new javax.swing.GroupLayout(pnCenter1);
        pnCenter1.setLayout(pnCenter1Layout);
        pnCenter1Layout.setHorizontalGroup(
            pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenter1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCenter1Layout.createSequentialGroup()
                        .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnCenter1Layout.createSequentialGroup()
                        .addComponent(lblType)
                        .addGap(12, 12, 12)
                        .addComponent(chebBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chebNewpapers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chebJournalsandMagazines))
                    .addGroup(pnCenter1Layout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addGap(55, 55, 55)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCenter1Layout.createSequentialGroup()
                        .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblContactNo)
                            .addComponent(lblRemarks))
                        .addGap(34, 34, 34)
                        .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsrpRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtContactNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnCenter1Layout.setVerticalGroup(
            pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenter1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(chebBooks)
                    .addComponent(chebNewpapers)
                    .addComponent(chebJournalsandMagazines))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNo)
                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCenter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRemarks)
                    .addComponent(jsrpRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pnCentre2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNew.setBackground(new java.awt.Color(0, 102, 51));
        btnNew.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 102, 0));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 102, 0));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCentre2Layout = new javax.swing.GroupLayout(pnCentre2);
        pnCentre2.setLayout(pnCentre2Layout);
        pnCentre2Layout.setHorizontalGroup(
            pnCentre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCentre2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCentre2Layout.setVerticalGroup(
            pnCentre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCentre2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCentre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout pnLastLayout = new javax.swing.GroupLayout(pnLast);
        pnLast.setLayout(pnLastLayout);
        pnLastLayout.setHorizontalGroup(
            pnLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnLastLayout.setVerticalGroup(
            pnLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLastLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnfirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnCentre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnCenter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCenter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCentre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       Connection conn = null;
        String strBook="";
        String strNewsPape="";
        String strJornals="";
        if(chebBooks.isSelected())
            strBook="Books";
        if(chebNewpapers.isSelected())
            strNewsPape="Newspapers";
        if(chebJournalsandMagazines.isSelected())
            strJornals="JournalsandMagazines";
        PreparedStatement stmt = null;
        try {
            conn=DriverManager.getConnection(url,user,pass);
             String sql = " update books set name='"+txtName.getText()+"',books='"+strBook+"',newspapers='"+strNewsPape+"',journalsandmagazines='"+strJornals+"',address='"+txtAddress.getText()+"',contact='"+txtContactNo.getText()+"',email='"+txtEmail.getText()+"',remarks='"+jTxtaRemarks.getText()+"'where id="+txtID.getText();
             
            stmt = conn.prepareStatement(sql);
             int rows = stmt.executeUpdate();
             System.out.println("update succeedfull : " + rows );
             
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(BookSuppliers.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        btnDelete.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(true);
        loadData();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        String strBook="";
        String strNewsPape="";
        String strJornals="";
        if(chebBooks.isSelected())
            strBook="Books";
        if(chebNewpapers.isSelected())
            strNewsPape="Newspapers";
        if(chebJournalsandMagazines.isSelected())
            strJornals="JournalsandMagazines";
        PreparedStatement stmt = null;
        try {
            conn=DriverManager.getConnection(url,user,pass);
             String sql = "insert into books values('"+txtName.getText()+"','"+strBook+"','"+strJornals+"','"+strNewsPape+"','"+txtAddress.getText()+"','"+txtContactNo.getText()+"','"+txtEmail.getText()+"','"+jTxtaRemarks.getText()+"')";
            stmt = conn.prepareStatement(sql);
             int rows = stmt.executeUpdate();
             System.out.println("insert succeedfull : " + rows );
             conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(BookSuppliers.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
        String strBook="";
        String strNewsPape="";
        String strJornals="";
        if(chebBooks.isSelected())
            strBook="Books";
        if(chebNewpapers.isSelected())
            strNewsPape="Newspapers";
        if(chebJournalsandMagazines.isSelected())
            strJornals="JournalsandMagazines";
        PreparedStatement stmt = null;
        try {
            conn=DriverManager.getConnection(url,user,pass);
             String sql = "delete from books where id="+txtID.getText();
            stmt = conn.prepareStatement(sql);
             int rows = stmt.executeUpdate();
             System.out.println("delete succeedfull : " + rows );
             conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(BookSuppliers.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_formComponentShown
  
    private void loadData(){
        try {
            tblData.removeAll();
            String[] arr= {"Supplier ID","Supplier Name","Books","Newspapers","Journals and Magazines","Address","Contact No","Email ID","Remarks"};
            String sql="select *from books";
            DefaultTableModel model=new DefaultTableModel(arr,0);
            Connection conn=DriverManager.getConnection(url, user, pass);
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
            while(rs.next())
            {
                Vector vector=new Vector();
                vector.add(rs.getInt(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                vector.add(rs.getString(6));
                vector.add(rs.getString(7));
                vector.add(rs.getString(8));
                model.addRow(vector);
                
            }
            tblData.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(BookSuppliers.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
        
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSuppliers().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chebBooks;
    private javax.swing.JCheckBox chebJournalsandMagazines;
    private javax.swing.JCheckBox chebNewpapers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtaRemarks;
    private javax.swing.JScrollPane jsrpRemarks;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JPanel pnCenter1;
    private javax.swing.JPanel pnCentre2;
    private javax.swing.JPanel pnLast;
    private javax.swing.JPanel pnfirst;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
