/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai7practices;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author KHA
 */
public class ThaoTacJlistJcheckBox extends javax.swing.JFrame {

    /**
     * Creates new form ThaoTacJlistJcheckBox
     */
    public ThaoTacJlistJcheckBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBorder = new javax.swing.JPanel();
        pnNorth = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        btnNhap = new javax.swing.JButton();
        txtNhap = new javax.swing.JTextField();
        checkb = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSo = new javax.swing.JList<>();
        pnWest = new javax.swing.JPanel();
        btnTodenSoChan = new javax.swing.JButton();
        btnTodenSoLe = new javax.swing.JButton();
        btnTodenSoNguyenTo = new javax.swing.JButton();
        btnBotoDen = new javax.swing.JButton();
        btnXoaCacGiaTriToden = new javax.swing.JButton();
        btnTongGiaTriTrongJlist = new javax.swing.JButton();
        pnSouth = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnBorder.setLayout(new java.awt.BorderLayout());

        lbTitle.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Thao tác trên Jlist -JCheckBox");

        javax.swing.GroupLayout pnNorthLayout = new javax.swing.GroupLayout(pnNorth);
        pnNorth.setLayout(pnNorthLayout);
        pnNorthLayout.setHorizontalGroup(
            pnNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNorthLayout.setVerticalGroup(
            pnNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnBorder.add(pnNorth, java.awt.BorderLayout.NORTH);

        pnCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null), "Nhập Thông Tin :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        btnNhap.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        txtNhap.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        checkb.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        checkb.setText("Cho nhập số âm");

        jListSo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jListSo.setEnabled(false);
        jScrollPane1.setViewportView(jListSo);

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkb)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhap)
                    .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );

        pnBorder.add(pnCenter, java.awt.BorderLayout.CENTER);

        pnWest.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), null), "Chọn Tác Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N
        pnWest.setAlignmentY(1.5F);
        pnWest.setLayout(new javax.swing.BoxLayout(pnWest, javax.swing.BoxLayout.Y_AXIS));

        btnTodenSoChan.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnTodenSoChan.setText("Tô đen số chẵn");
        btnTodenSoChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenSoChanActionPerformed(evt);
            }
        });
        pnWest.add(btnTodenSoChan);

        btnTodenSoLe.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnTodenSoLe.setText("Tô đen số Lẻ");
        pnWest.add(btnTodenSoLe);

        btnTodenSoNguyenTo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnTodenSoNguyenTo.setText("Tô đen số Nguyên Tố");
        pnWest.add(btnTodenSoNguyenTo);

        btnBotoDen.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnBotoDen.setText("Bỏ tô đen");
        pnWest.add(btnBotoDen);

        btnXoaCacGiaTriToden.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnXoaCacGiaTriToden.setText("Xóa các giá trị tô đen");
        pnWest.add(btnXoaCacGiaTriToden);

        btnTongGiaTriTrongJlist.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnTongGiaTriTrongJlist.setText("Tổng giá trị trong Jlist");
        pnWest.add(btnTongGiaTriTrongJlist);

        pnBorder.add(pnWest, java.awt.BorderLayout.WEST);

        pnSouth.setBackground(new java.awt.Color(153, 255, 204));
        pnSouth.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        pnSouth.setRequestFocusEnabled(false);
        pnSouth.setVerifyInputWhenFocusTarget(false);

        btnClose.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnClose.setText("đóng chương trình");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSouthLayout = new javax.swing.GroupLayout(pnSouth);
        pnSouth.setLayout(pnSouthLayout);
        pnSouthLayout.setHorizontalGroup(
            pnSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSouthLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        pnSouthLayout.setVerticalGroup(
            pnSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSouthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBorder.add(pnSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int n= JOptionPane.showConfirmDialog(null,"Bạn Chắc Chắn chứ! ","Note!! ",JOptionPane.YES_NO_OPTION);
        System.out.print(n);
        if(n==JOptionPane.YES_OPTION)
            System.exit(0);
        else 
            new ThaoTacJlistJcheckBox();
            

    }//GEN-LAST:event_btnCloseActionPerformed
    DefaultListModel dlm= new DefaultListModel();
    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        // TODO add your handling code here
        long a=Long.parseLong(this.txtNhap.getText());
        if(!this.checkb.isSelected()&&a<0)
        {   
            JOptionPane.showMessageDialog(null,"số nhâp không âm vui lòng nhập lai hoặc click vào ''cho nhập số âm''");
        }else
        {
        dlm.addElement(a);
        this.jListSo.setModel(dlm);
        this.txtNhap.setText("");
        }
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnTodenSoChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenSoChanActionPerformed
        // TODO add your handling code here:
       // for(int i=0;i<this.jListSo.getFixedCellHeight();i++)
         
       
    }//GEN-LAST:event_btnTodenSoChanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThaoTacJlistJcheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThaoTacJlistJcheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThaoTacJlistJcheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThaoTacJlistJcheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThaoTacJlistJcheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotoDen;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnTodenSoChan;
    private javax.swing.JButton btnTodenSoLe;
    private javax.swing.JButton btnTodenSoNguyenTo;
    private javax.swing.JButton btnTongGiaTriTrongJlist;
    private javax.swing.JButton btnXoaCacGiaTriToden;
    private javax.swing.JCheckBox checkb;
    private javax.swing.JList<String> jListSo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnBorder;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnNorth;
    private javax.swing.JPanel pnSouth;
    private javax.swing.JPanel pnWest;
    private javax.swing.JTextField txtNhap;
    // End of variables declaration//GEN-END:variables
}
