/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MayTinhBoTui;

/**
 *
 * @author KHA
 */
public class Jframe extends javax.swing.JFrame {

    /**
     * Creates new form Jframe
     */
    public Jframe() {
        super("Calculator");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        hienThi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 5));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("1");
        jPanel1.add(jButton5);

        jButton12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton12.setText("2");
        jPanel1.add(jButton12);

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton7.setText("3");
        jPanel1.add(jButton7);

        jButton19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton19.setText("/");
        jPanel1.add(jButton19);

        jButton15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton15.setText("sqrt");
        jPanel1.add(jButton15);

        jButton14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton14.setText("4");
        jPanel1.add(jButton14);

        jButton24.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton24.setText("5");
        jPanel1.add(jButton24);

        jButton25.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton25.setText("6");
        jPanel1.add(jButton25);

        jButton26.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton26.setText("*");
        jPanel1.add(jButton26);

        jButton27.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton27.setText("%");
        jPanel1.add(jButton27);

        jButton28.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton28.setText("7");
        jPanel1.add(jButton28);

        jButton29.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton29.setText("8");
        jPanel1.add(jButton29);

        jButton30.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton30.setText("9");
        jPanel1.add(jButton30);

        jButton31.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton31.setText("-");
        jPanel1.add(jButton31);

        jButton32.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton32.setText("1/x");
        jPanel1.add(jButton32);

        jButton33.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton33.setText("0");
        jPanel1.add(jButton33);

        jButton34.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton34.setText("+/-");
        jPanel1.add(jButton34);

        jButton35.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton35.setText("C");
        jPanel1.add(jButton35);

        jButton36.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton36.setText("-");
        jPanel1.add(jButton36);

        jButton37.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton37.setText("=");
        jPanel1.add(jButton37);

        hienThi.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        hienThi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hienThi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(hienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hienThi;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
