/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TroChoiXepO;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author KHA
 */
public class TroChoiXepO extends javax.swing.JFrame {
    private String a="";
    /**
     * Creates new form TroChoiXepO
     */
    public TroChoiXepO() {
     String m = JOptionPane.showInputDialog("Name : ");
        System.out.println(m);
        this.setTitle(m);
        this.setSize(400,400);
        this.setLocationRelativeTo(null);
       
        initComponents();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBorder = new javax.swing.JPanel();
        pnFrist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        so10 = new javax.swing.JButton();
        so11 = new javax.swing.JButton();
        so12 = new javax.swing.JButton();
        so13 = new javax.swing.JButton();
        so14 = new javax.swing.JButton();
        so15 = new javax.swing.JButton();
        soNull = new javax.swing.JButton();
        pnLast = new javax.swing.JPanel();
        btnstart = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(640, 360));

        pnBorder.setLayout(new java.awt.BorderLayout());

        pnFrist.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Puzzle Game of Fifteen");
        pnFrist.add(jLabel1);

        pnBorder.add(pnFrist, java.awt.BorderLayout.PAGE_START);

        pnCenter.setPreferredSize(new java.awt.Dimension(640, 360));
        pnCenter.setLayout(new java.awt.GridLayout(4, 4));

        so1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so1.setText("1");
        so1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so1.setContentAreaFilled(false);
        so1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so1.setEnabled(false);
        so1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        pnCenter.add(so1);

        so2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so2.setText("2");
        so2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so2.setContentAreaFilled(false);
        so2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so2.setEnabled(false);
        so2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so2ActionPerformed(evt);
            }
        });
        pnCenter.add(so2);

        so3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so3.setText("3");
        so3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so3.setContentAreaFilled(false);
        so3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so3.setEnabled(false);
        so3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so3ActionPerformed(evt);
            }
        });
        pnCenter.add(so3);

        so4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so4.setText("4");
        so4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so4.setContentAreaFilled(false);
        so4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so4.setEnabled(false);
        so4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so4ActionPerformed(evt);
            }
        });
        pnCenter.add(so4);

        so5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so5.setText("5");
        so5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so5.setContentAreaFilled(false);
        so5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so5.setEnabled(false);
        so5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so5ActionPerformed(evt);
            }
        });
        pnCenter.add(so5);

        so6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so6.setText("6");
        so6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so6.setContentAreaFilled(false);
        so6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so6.setEnabled(false);
        so6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so6ActionPerformed(evt);
            }
        });
        pnCenter.add(so6);

        so7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so7.setText("7");
        so7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so7.setContentAreaFilled(false);
        so7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so7.setEnabled(false);
        so7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so7ActionPerformed(evt);
            }
        });
        pnCenter.add(so7);

        so8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so8.setText("8");
        so8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so8.setContentAreaFilled(false);
        so8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so8.setEnabled(false);
        so8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so8ActionPerformed(evt);
            }
        });
        pnCenter.add(so8);

        so9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so9.setText("9");
        so9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so9.setContentAreaFilled(false);
        so9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so9.setEnabled(false);
        so9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so9ActionPerformed(evt);
            }
        });
        pnCenter.add(so9);

        so10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so10.setText("10");
        so10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so10.setContentAreaFilled(false);
        so10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so10.setEnabled(false);
        so10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so10ActionPerformed(evt);
            }
        });
        pnCenter.add(so10);

        so11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so11.setText("11");
        so11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so11.setContentAreaFilled(false);
        so11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so11.setEnabled(false);
        so11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so11ActionPerformed(evt);
            }
        });
        pnCenter.add(so11);

        so12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so12.setText("12");
        so12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so12.setContentAreaFilled(false);
        so12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so12.setEnabled(false);
        so12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so12ActionPerformed(evt);
            }
        });
        pnCenter.add(so12);

        so13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so13.setText("13");
        so13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so13.setContentAreaFilled(false);
        so13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so13.setEnabled(false);
        so13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so13ActionPerformed(evt);
            }
        });
        pnCenter.add(so13);

        so14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so14.setText("14");
        so14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so14.setContentAreaFilled(false);
        so14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so14.setEnabled(false);
        so14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so14ActionPerformed(evt);
            }
        });
        pnCenter.add(so14);

        so15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        so15.setText("15");
        so15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so15.setContentAreaFilled(false);
        so15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        so15.setEnabled(false);
        so15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        so15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so15ActionPerformed(evt);
            }
        });
        pnCenter.add(so15);

        soNull.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        soNull.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        soNull.setContentAreaFilled(false);
        soNull.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        soNull.setEnabled(false);
        soNull.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        soNull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soNullActionPerformed(evt);
            }
        });
        pnCenter.add(soNull);

        pnBorder.add(pnCenter, java.awt.BorderLayout.CENTER);

        btnstart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnstart.setText("Start");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });
        pnLast.add(btnstart);

        btnCheck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        pnLast.add(btnCheck);

        pnBorder.add(pnLast, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBorder, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBorder, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void so5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so5ActionPerformed
        // TODO add your handling code here:
         if(this.so1.getText()=="")
        {
        this.so1.setText(this.so5.getText());
        this.so5.setText(a);
        this.a="";
        }
          else if(this.so6.getText()=="")
        {this.so6.setText(this.so5.getText());
        this.so5.setText(a);
        this.a="";
        }
          else if(this.so9.getText()=="")
        {
        this.so9.setText(this.so5.getText());
        this.so5.setText(a);
        this.a="";
        }
    }//GEN-LAST:event_so5ActionPerformed

       
    private void so12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so12ActionPerformed
        // TODO add your handling code here:
         if(this.so8.getText()=="")
        {
        this.so8.setText(this.so12.getText());
        this.so12.setText(a);
        this.a="";
        }
          else if(this.so11.getText()=="")
        {this.so11.setText(this.so12.getText());
        this.so12.setText(a);
        this.a="";
        }
          else if(this.soNull.getText()=="")
        {
        this.soNull.setText(this.so12.getText());
        this.so12.setText(a);
        this.a="";
        }
    }//GEN-LAST:event_so12ActionPerformed

    private void soNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soNullActionPerformed
        // TODO add your handling code here:
        
        
        if(this.so12.getText()=="")
        {
        this.so12.setText(this.soNull.getText());
        this.soNull.setText(a);
        this.a="";
        }
        
        else if(this.so15.getText()=="")
        {
        this.so15.setText(this.soNull.getText());
        this.soNull.setText(a);
        this.a="";
        }
    }//GEN-LAST:event_soNullActionPerformed

    private void so15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so15ActionPerformed
        // TODO add your handling code here:
         
         if(this.so14.getText()=="")
        {
        this.so14.setText(this.so15.getText());
        this.so15.setText(a);
        this.a="";
        }
          else if(this.so11.getText()=="")
        {this.so11.setText(this.so15.getText());
        this.so15.setText(a);
        this.a="";
        }
          else if(soNull.getText()=="")
        {
        this.soNull.setText(this.so15.getText());
        this.so15.setText(a);
        this.a="";
        }
        
    }//GEN-LAST:event_so15ActionPerformed

    private void so14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so14ActionPerformed
        // TODO add your handling code here:
         if(this.so10.getText()=="")
        {
        this.so10.setText(this.so14.getText());
        this.so14.setText(a);
        this.a="";
        }
          else if(this.so13.getText()=="")
        {this.so13.setText(this.so14.getText());
        this.so14.setText(a);
        this.a="";
        }
          else if(this.so15.getText()=="")
        {
        this.so15.setText(this.so14.getText());
        this.so14.setText(a);
        this.a="";
        }
    }//GEN-LAST:event_so14ActionPerformed

    private void so11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so11ActionPerformed
        // TODO add your handling code here:
         if(this.so15.getText()=="")
        {
        this.so15.setText(this.so11.getText());
        this.so11.setText(a);
        this.a="";
        }
          else if(this.so10.getText()=="")
        {this.so10.setText(this.so11.getText());
        this.so11.setText(a);
        this.a="";
        }
          else if(this.so7.getText()=="")
        {
        this.so7.setText(this.so11.getText());
        this.so11.setText(a);
        this.a="";
        }  else if(this.so12.getText()=="")
        {
        this.so12.setText(this.so11.getText());
        this.so11.setText(a);
        this.a="";
        } 
 
    }//GEN-LAST:event_so11ActionPerformed

    private void so10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so10ActionPerformed
        // TODO add your handling code here:
         if(this.so6.getText()=="")
        {
        this.so6.setText(this.so10.getText());
        this.so10.setText(a);
        this.a="";
        }
          else if(this.so9.getText()=="")
        {this.so9.setText(this.so10.getText());
        this.so10.setText(a);
        this.a="";
        }
          else if(this.so14.getText()=="")
        {
        this.so14.setText(this.so10.getText());
        this.so10.setText(a);
        this.a="";
        }  else if(this.so11.getText()=="")
        {
        this.so11.setText(this.so10.getText());
        this.so10.setText(a);
        this.a="";
        }  

    }//GEN-LAST:event_so10ActionPerformed

    private void so9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so9ActionPerformed
        // TODO add your handling code here:
         if(this.so5.getText()=="")
        {
        this.so5.setText(this.so9.getText());
        this.so9.setText(a);
        this.a="";
        }
          else if(this.so10.getText()=="")
        {this.so10.setText(this.so9.getText());
        this.so9.setText(a);
        this.a="";
        }
          else if(this.so13.getText()=="")
        {
        this.so13.setText(this.so9.getText());
        this.so9.setText(a);
        this.a="";
        } 
     
    }//GEN-LAST:event_so9ActionPerformed

    private void so13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so13ActionPerformed
        // TODO add your handling code here:
         if(this.so14.getText()=="")
        {
        this.so14.setText(this.so13.getText());
        this.so13.setText(a);
        this.a="";
        }
          else if(this.so9.getText()=="")
        {this.so9.setText(this.so13.getText());
        this.so13.setText(a);
        this.a="";
        }
       
    }//GEN-LAST:event_so13ActionPerformed

    private void so8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so8ActionPerformed
        // TODO add your handling code here:
         if(this.so7.getText()=="")
        {
        this.so7.setText(this.so8.getText());
        this.so8.setText(a);
        this.a="";
        }
          else if(this.so4.getText()=="")
        {this.so4.setText(this.so8.getText());
        this.so8.setText(a);
        this.a="";
        }
          else if(this.so12.getText()=="")
        {
        this.so12.setText(this.so8.getText());
        this.so8.setText(a);
        this.a="";
        }
    }//GEN-LAST:event_so8ActionPerformed

    private void so7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so7ActionPerformed
        // TODO add your handling code here:
         if(this.so3.getText()=="")
        {
        this.so3.setText(this.so7.getText());
        this.so7.setText(a);
        this.a="";
        }
          else if(this.so6.getText()=="")
        {this.so6.setText(this.so7.getText());
        this.so7.setText(a);
        this.a="";
        }
          else if(this.so11.getText()=="")
        {
        this.so11.setText(this.so7.getText());
        this.so7.setText(a);
        this.a="";
        } else if(this.so8.getText()=="")
        {
        this.so8.setText(this.so7.getText());
        this.so7.setText(a);
        this.a="";
        }

    }//GEN-LAST:event_so7ActionPerformed

    private void so6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so6ActionPerformed
        // TODO add your handling code here:
         if(this.so2.getText()=="")
        {
        this.so2.setText(this.so6.getText());
        this.so6.setText(a);
        this.a="";
        }
          else if(this.so5.getText()=="")
        {this.so5.setText(this.so6.getText());
        this.so6.setText(a);
        this.a="";
        }
          else if(this.so10.getText()=="")
        {
        this.so10.setText(this.so6.getText());
        this.so6.setText(a);
        this.a="";
        } else if(this.so7.getText()=="")
        {
        this.so7.setText(this.so6.getText());
        this.so6.setText(a);
        this.a="";
        }

    }//GEN-LAST:event_so6ActionPerformed

    private void so4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so4ActionPerformed
        // TODO add your handling code here:
         if(this.so3.getText()=="")
        {
        this.so3.setText(this.so4.getText());
        this.so4.setText(a);
        this.a="";
        }
          else if(this.so8.getText()=="")
        {this.so8.setText(this.so4.getText());
        this.so4.setText(a);
        this.a="";
        }

    }//GEN-LAST:event_so4ActionPerformed

    private void so3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so3ActionPerformed
        // TODO add your handling code here:
         if(this.so2.getText()=="")
        {
        this.so2.setText(this.so3.getText());
        this.so3.setText(a);
        this.a="";
        }
          else if(this.so7.getText()=="")
        {this.so7.setText(this.so3.getText());
        this.so3.setText(a);
        this.a="";
        }
          else if(this.so4.getText()=="")
        {
        this.so4.setText(this.so3.getText());
        this.so3.setText(a);
        this.a="";
        }
    
    }//GEN-LAST:event_so3ActionPerformed

    private void so2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so2ActionPerformed
        // TODO add your handling code here:
         if(this.so1.getText()=="")
        {
        this.so1.setText(this.so2.getText());
        this.so2.setText(a);
        this.a="";
        }
          else if(this.so6.getText()=="")
        {this.so6.setText(this.so2.getText());
        this.so2.setText(a);
        this.a="";
        }
          else if(this.so3.getText()=="")
        {
        this.so3.setText(this.so2.getText());
        this.so2.setText(a);
        this.a="";
        }
         
    }//GEN-LAST:event_so2ActionPerformed

    private void so1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so1ActionPerformed
        // TODO add your handling code here:
         if(this.so5.getText()=="")
        {
        this.so5.setText(this.so1.getText());
        this.so1.setText(a);
        this.a="";
        }
          else if(this.so2.getText()=="")
        {this.so2.setText(this.so1.getText());
        this.so1.setText(a);
        this.a="";
        }
        
    }//GEN-LAST:event_so1ActionPerformed

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        // TODO add your handling code here:
         so1.setEnabled(true);
        so2.setEnabled(true);
        so3.setEnabled(true);
        so4.setEnabled(true);
        so5.setEnabled(true);
        so6.setEnabled(true);
        so7.setEnabled(true);
        so8.setEnabled(true);
        so9.setEnabled(true);
        so10.setEnabled(true);
        so11.setEnabled(true);
        so12.setEnabled(true);
        so13.setEnabled(true);
        so14.setEnabled(true);
        so15.setEnabled(true);
        soNull.setEnabled(true); 
      java.util.List<Integer> x = new ArrayList();

        for(int i = 0; i < 15; i++){
            x.add(i+1);
        }

        java.util.Collections.shuffle(x);
        this.so1.setText(String.valueOf(x.get(0)));
        this.so2.setText(String.valueOf(x.get(1)));
        this.so3.setText(String.valueOf(x.get(2)));
        this.so4.setText(String.valueOf(x.get(3)));
        this.so5.setText(String.valueOf(x.get(4)));
        this.so6.setText(String.valueOf(x.get(5)));
        this.so7.setText(String.valueOf(x.get(6)));
        this.so8.setText(String.valueOf(x.get(7)));
        this.so9.setText(String.valueOf(x.get(8)));
        this.so10.setText(String.valueOf(x.get(9)));
        this.so11.setText(String.valueOf(x.get(10)));
        this.so12.setText(String.valueOf(x.get(11)));
        this.so13.setText(String.valueOf(x.get(12)));
        this.so14.setText(String.valueOf(x.get(13)));
        this.so15.setText(String.valueOf(x.get(14)));
        this.soNull.setText("");
    }//GEN-LAST:event_btnstartActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
         if(this.so1.getText()=="1"&&this.so2.getText()=="2"&&this.so3.getText()=="3"&&this.so4.getText()=="4"&&this.so5.getText()=="5"&&
                this.so6.getText()=="6"&&this.so7.getText()=="7"&&this.so8.getText()=="8"&&this.so9.getText()=="9"&&this.so10.getText()=="10"&&
                this.so11.getText()=="11"&&this.so12.getText()=="12"&&this.so13.getText()=="13"&&this.so14.getText()=="14"&&this.so15.getText()=="15"
                &&this.soNull.getText()=="")
        {
          
            int n= JOptionPane.showConfirmDialog(null, "You Win and You want to Play again!",
                  "Title", JOptionPane.YES_NO_OPTION);
            System.out.print(n);
             if(n==JOptionPane.YES_OPTION)
             {
                new TroChoiXepO();   
             }else
             {
                 JOptionPane.showMessageDialog(null,"thanks....");
                 System.exit(0);
             }
            
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TroChoiXepO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TroChoiXepO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TroChoiXepO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TroChoiXepO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TroChoiXepO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnBorder;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnFrist;
    private javax.swing.JPanel pnLast;
    private javax.swing.JButton so1;
    private javax.swing.JButton so10;
    private javax.swing.JButton so11;
    private javax.swing.JButton so12;
    private javax.swing.JButton so13;
    private javax.swing.JButton so14;
    private javax.swing.JButton so15;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    private javax.swing.JButton soNull;
    // End of variables declaration//GEN-END:variables
}
